#!/bin/sh
set -e
src="$(cd "$(dirname "$0")" && pwd)/70-usbasp.rules"
sudo rm -f /etc/udev/rules.d/99-usbasp.rules
sudo cp "$src" /etc/udev/rules.d/70-usbasp.rules
sudo udevadm control --reload-rules
echo "Unplug and replug USBasp."
